
services:
  - type: web
    runtime: docker
    name: digital-birth-certificate
    
    plan: free
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:80 -t public
    envVars:
      - key: APP_ENV
        value: production